### ISSUE TITLE
Form field description translations show two languages at the same time

### ISSUE THREAD

**Issue by 2xG** [owen2345/cama_contact_form#5]
I've made a contact form with no custom rendering: (sorry for a large image)
![admin_panel_contact_form_edit_contact_form](https://cloud.githubusercontent.com/assets/1117339/20629992/72fd10ec-b2fc-11e6-9951-b04e79e82d91.png)
Then I've made a page containing the form shortcode `[forms slug=pew-pew-pew]`
And I get this when I open this page.
![selection_024](https://cloud.githubusercontent.com/assets/1117339/20630108/1657faf4-b2fd-11e6-9af3-28dad488ffb9.png)
The labels are translated as it has to be, but description is duplicated.
```html
<p><!--:en-->present yourself<!--:--><!--:es-->presentese<!--:--></p>
```
As I see in source code gems/cama_contact_form-0.0.12/app/helpers/plugins/cama_contact_form/[main_helper.rb](https://github.com/owen2345/cama_contact_form/blob/master/app/helpers/plugins/cama_contact_form/main_helper.rb) the translation is made the same way, but I wonder why it has different output.

```ruby
  def cama_form_element_bootstrap_object(form, object, values)
    html = ""
    object.each do |ob|
      ob[:label] = ob[:label].to_s.translate
      ob[:description] = ob[:description].to_s.translate
      ...
    end
    html
  end
```

Thanks in advance!

**Comment by owen2345** [comment]
Fixed!

**Comment by 2xG** [comment]
Thanks @owen2345 it works!
I've found more translation issues:
![selection_025](https://cloud.githubusercontent.com/assets/1117339/20634876/873908b4-b323-11e6-81b3-066dc0a9481c.png)

And default system Submit button also keeps showing "Send" text with locale changed.

**Comment by owen2345** [comment]
Fixed!

**Comment by 2xG** [comment]
I've made a pull request fixing this error https://github.com/owen2345/cama_contact_form/pull/6
